version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    working_dir: /application
    restart: unless-stopped
    volumes:
      - .:/application
      - ./storage-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bry_api
      - MYSQL_USER=bry
      - MYSQL_PASSWORD=123456
    ports:
      - "8083:3306"

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    restart: unless-stopped
    volumes:
     - .:/application
     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
       - "80:80"
       - "443:443"
    links:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: bryapp
    working_dir: /application
    restart: unless-stopped
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
